#!/bin/bash
cd /Users/bhauman/workspace/specly

sed -i.bak -e 's/strictly-specking/strictly-specking-standalone/g' -e 's/clojure.spec/strictly-specking-standalone.spec/g' test/strictly_specking/*.clj src/strictly_specking/*.clj
rm test/strictly_specking/*.bak rm src/strictly_specking/*.bak

mv test/strictly_specking test/strictly_specking_standalone
mv src/strictly_specking src/strictly_specking_standalone

#sed -i.bak -e 's/strictly-specking/strictly-specking-standalone/g' -e 's/clojure.spec/strictly-specking-standalone.spec/g' src/strictly_specking/*.clj
# rm src/strictly_specking/*.bak
#mv src/strictly_specking src/strictly_specking_standalone

#sed -i.bak -e 's/strictly-specking/strictly-specking-standalone/g' -e  src/1.6_compat_spec/spec.clj src/1.6_compat_spec/spec/gen.clj


