#!/bin/bash

mv test/strictly_specking_standalone test/strictly_specking
mv src/strictly_specking_standalone src/strictly_specking

sed -i.bak -e 's/strictly-specking-standalone.spec/clojure.spec/g' -e 's/strictly-specking-standalone/strictly-specking/g' test/strictly_specking/*.clj src/strictly_specking/*.clj

rm test/strictly_specking/*.bak src/strictly_specking/*.bak


